# Generated by Django 3.0.8 on 2020-07-17 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionWindow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "windows_starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the permission window begins.",
                    ),
                ),
                (
                    "window_ends_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the permission window ends.",
                    ),
                ),
                (
                    "window_type",
                    models.CharField(
                        choices=[("OPEN", "Open-ended"), ("CLOSED", "Hard-stop")],
                        default="OPEN",
                        help_text="How the window end timestamp should be treated.",
                        max_length=10,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Kill switch for permission window."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the database record was created.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonate_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
